
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Oct 16 2021 20:44:54 IST (Oct 16 2021 15:14:54 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, Q0, Q1, Q2);
  input clk, reset;
  output Q0, Q1, Q2;
  wire clk, reset;
  wire Q0, Q1, Q2;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  NR2M2R g198(.A (reset), .B (n_5), .Z (n_6));
  AOI32M2R g200(.A1 (n_0), .A2 (Q0), .A3 (Q1), .B1 (n_3), .B2 (Q2), .Z
       (n_5));
  NR2B1M2R g202(.B (reset), .NA (n_3), .Z (n_4));
  DFCQM2RA \y_reg[0] (.CKB (clk), .D (n_2), .Q (Q0));
  MXB2M1RA g204(.A (n_1), .B (Q1), .S (Q0), .Z (n_3));
  AOI211M2R g203(.A1 (n_1), .A2 (Q2), .B (reset), .C (Q0), .Z (n_2));
  DFCM2RA \y_reg[1] (.CKB (clk), .D (n_4), .Q (Q1), .QB (n_1));
  DFCM2RA \y_reg[2] (.CKB (clk), .D (n_6), .Q (Q2), .QB (n_0));
endmodule

